### ISSUE TITLE
pkg-config is not being picked up by meson when building FreeType

### ISSUE THREAD

**Issue by xelibrion** [m154k1/mpv-build-macOS#1]
Curious why this would be the case?

```
./build-FreeType -Dharfbuzz=disabled                                                                       master
WARNING import_local_pkg: /Users/xelibrion/projects/mpv-builds/freetype/lib/pkgconfig does not exist.
The Meson build system
Version: 1.2.2
Source dir: /Users/xelibrion/projects/mpv-build-macOS/src/freetype
Build dir: /private/var/folders/mr/45km409j5kj9wwrybrw90f6m0000gn/T/build.freetype
Build type: native build
Project name: freetype2
Project version: 2.13.2
C compiler for the host machine: cc (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.0.40.1)")
C linker for the host machine: cc ld64 1015.7
Host machine cpu family: aarch64
Host machine cpu: aarch64
Program python3 found: YES (/Users/xelibrion/anaconda3/bin/python3)
Has header "unistd.h" : YES
Has header "fcntl.h" : YES
Has header "sys/mman.h" : YES
Did not find pkg-config by name 'pkgconf'
Found Pkg-config: NO
Found CMake: /Users/xelibrion/homebrew/bin/cmake (3.27.7)
Run-time dependency zlib found: YES 1.2.12
Library bz2 found: YES
Run-time dependency libpng found: NO (tried pkgconfig, framework and cmake)
Looking for a fallback subproject for the dependency libpng

src/freetype/meson.build:329:13: ERROR: Automatic wrap-based subproject downloading is disabled
```

```
mpv-build-macOS ➜ which pkg-config                                                                                          
/Users/xelibrion/homebrew/bin/pkg-config
```

```
mpv-build-macOS ➜ pkg-config --libs --cflags libpng                                                                         
-I/Users/xelibrion/homebrew/opt/libpng/include/libpng16 -L/Users/xelibrion/homebrew/opt/libpng/lib -lpng16
```

Full log here https://pastebin.com/HpsnE6ff

**Comment by m154k1** [comment]
I'm using [pkgconf](https://github.com/pkgconf/pkgconf) instead of pkg-config.
You can get pkgconf from [Homebrew](https://formulae.brew.sh/formula/pkgconf#default).

If you want to use pkg-config change `pkgconf` to `pkg-config` here:
https://github.com/m154k1/mpv-build-macOS/blob/b799ce18bd323b58f62672e71adbc9834d53a086/build.env#L1

**Comment by N-R-K** [comment]
> I'm using [pkgconf](https://github.com/pkgconf/pkgconf) instead of pkg-config.
> You can get pkgconf from [Homebrew](https://formulae.brew.sh/formula/pkgconf#default).

Does it not add a `pkg-config` symlink? It should, since that's supposed to be the name of the binary.

**Comment by m154k1** [comment]
Unfortunately, Homebrew doesn't add a symlink unlike most Linux distros.

The binary name is `pkgconf` for some reason:
https://github.com/pkgconf/pkgconf#pkg-config-symlink

**Comment by N-R-K** [comment]
> Unfortunately, Homebrew doesn't add a symlink unlike most Linux distros.

Hmm I see.

> The binary name is `pkgconf` for some reason.

That seems fine, it should be up to the distribution to make the symlink. And to be clear, when I asked "Does it not [...]" I was talking about homebrew not pkgconf.

The reason why I mentioned it is because not every build supports `PKG_CONFIG` env var. Some just outright call `pkg-config` directly. So it's up to the distro/user to ensure the binary/symlink by that name exists. This is similar to how if you want to use [pigz](https://zlib.net/pigz/), it's up to you to make a `gzip` symlink to it. In my system for example, `pkg-config` is a symlink to [`u-config`](https://github.com/skeeto/u-config).

If homebrew doesn't make the symlink by default, then that's unfortunate. Maybe you can do something to dynamically probe for `pkg-config` => `pkgconf`?

**Comment by m154k1** [comment]
> Maybe you can do something to dynamically probe for `pkg-config` => `pkgconf`?

It's a good idea but I don't think it's necessary here.
pkgconf is part of the build dependencies so it _should be_ installed if [Preparation](https://github.com/m154k1/mpv-build-macOS#preparation) step 3 is done. Also everything used here supports `PKG_CONFIG` var.

This repo is more like a personal backup anyway.

**Comment by xelibrion** [comment]
> I'm using [pkgconf](https://github.com/pkgconf/pkgconf) instead of pkg-config. You can get pkgconf from [Homebrew](https://formulae.brew.sh/formula/pkgconf#default).
> 
> If you want to use pkg-config change `pkgconf` to `pkg-config` here:
> 
> https://github.com/m154k1/mpv-build-macOS/blob/b799ce18bd323b58f62672e71adbc9834d53a086/build.env#L1

What is interesting, I do have both `pkgconf` and `pkg-config` installed. But for some reason `pkgconf` was not present on the $PATH. 

```
mpv-build-macOS ➜ brew search pkgconf
==> Formulae
pkg-config ✔                                pkg-config-wrapper                          pkgconf ✔
```

I just reinstalled `pkgconf` and now FreeType compiles. Closing this issue.
